# -*- mode: ruby -*-
# vi: set ft=ruby :

# "2"는 Vagrant에서 루비로 코드를 읽어 들여 실행할 때 작동하는 API 버전이다.
# do |config|는 Vagrant 설정의 시작을 알린다.
Vagrant.configure("2") do |config|
  config.vm.define "m-k8s" do |cfg|             # 가상머신을 m-k8s로 정의하고, do |cfg|를 추가하여 원하는 설정으로 변경한다.
    cfg.vm.box = "sysnet4admin/CentOS-k8s"      # 기본값 config.vm.box를 do |cfg|에 적용한 내용을 받아 cfg.vm.box로 변경한다.
    # Vagrant의 Provide가 VirtualBox라는 것을 정의한다.
    # Provide는 Vagrant를 통해 제공되는 코드가 실제로 가상머신으로 배포되게 하는 소프트웨어이다.
    cfg.vm.provider "virtualbox" do |vb|
        vb.name = "m-k8s(github_SysNet4Admin)"  # 가상머신의 이름
        vb.cpus = 2                             # 가상머신의 CPU 수
        vb.memory = 2048                        # 가상머신의 메모리 크기
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]  # 가상머신이 소속된 그룹
    end
    cfg.vm.host_name = "m-k8s"  # 가상머신의 호스트 이름
    # 호스트 전용 네트워크를 private_network로 설정하여 eth1 인터페이스를 호스트 전용으로 구성하고 IP는 192.168.1.10으로 지정한다.
    cfg.vm.network "private_network", ip: "192.168.1.10"
    # ssh 통신을 호스트 60010번을 게스트 22번으로 전달되도록 구성한다.
    # 포트 중복을 대비하여 auto_correct: true로 설정해서 포트가 중복되면 포트가 자동으로 변경되도록 한다.
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    # 호스트와 게스트 사이에 디렉터리 동기화가 이루어지지 않게 설정한다.
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    # vm.provision "shell" 구문으로 경로에 있는 install_pkg.sh를 게스트 내부에서 호출하여 실행되도록 한다.
    cfg.vm.provision "shell", path: "install_pkg.sh"
    # 파일을 게스트 운영체제에 전달하기 위해 "shell"이 아닌 "file" 구문으로 변경한다.
    # 이렇게 하면 호스트에 있는 ping_2_nds.sh 파일을 게스트의 홈 디렉터리(/home/vagrant)로 전달한다.
    cfg.vm.provision "file", source: "ping_2_nds.sh", destination: "ping_2_nds.sh"
    # config.sh를 게스트에서 실행한다.
    cfg.vm.provision "shell", path: "config.sh"
  end


# Added Nodes #
  (1..3).each do |i|  # 1부터 3까지 3개의 인자를 반복하여 i로 입력
    config.vm.define "w#{i}-k8s" do |cfg| # {i}의 값이 1, 2, 3으로 차례대로 치환됨
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s(github_SysNet4Admin" # {i}의 값이 1, 2, 3으로 차례대로 치환됨
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "w#{i}-k8s"    # {i}의 값이 1, 2, 3으로 차례대로 치환됨
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"    # {i}의 값이 1, 2, 3으로 차례대로 치환됨
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"   # {i}의 값이 1, 2, 3으로 차례대로 치환됨
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "install_pkg.sh"
    end
  end
end